# Generated by Django 4.0.4 on 2022-06-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('idClase', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreClase', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('idHorario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreClase', models.CharField(max_length=40)),
                ('horarioClase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProfesor', models.CharField(max_length=40)),
                ('apellidoProfesor', models.CharField(max_length=40)),
                ('nombreClase', models.CharField(max_length=60)),
                ('fechaDeNacimientoProfesor', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('nombreSucursal', models.CharField(max_length=40)),
                ('direccionSucursal', models.CharField(max_length=40)),
                ('idSucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaDeInauguracionSucursal', models.DateField()),
            ],
        ),
    ]
