# Generated by Django 4.0.4 on 2022-07-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('idClase', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreClase', models.CharField(max_length=40)),
                ('sucursalClase', models.CharField(max_length=40)),
                ('profesorClase', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('idHorario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreClaseH', models.CharField(max_length=40)),
                ('horarioClase', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProfesor', models.CharField(max_length=40)),
                ('apellidoProfesor', models.CharField(max_length=40)),
                ('nombreClaseProfesor', models.CharField(max_length=60)),
                ('fechaDeNacimientoProfesor', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('nombreSucursal', models.CharField(max_length=40)),
                ('direccionSucursal', models.CharField(max_length=40)),
                ('idSucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaDeInauguracionSucursal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('cuerpo', tinymce.models.HTMLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
