# Generated by Django 4.0.4 on 2022-06-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='nombreClase',
            new_name='nombreClaseHorario',
        ),
        migrations.RenameField(
            model_name='profesores',
            old_name='nombreClase',
            new_name='nombreClaseProfesor',
        ),
    ]
