# Generated by Django 4.0.4 on 2022-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasios', '0002_rename_nombreclase_horarios_nombreclasehorario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='nombreClaseHorario',
            new_name='nombreClase',
        ),
        migrations.AlterField(
            model_name='horarios',
            name='horarioClase',
            field=models.CharField(max_length=40),
        ),
    ]
