# Generated by Django 4.0.4 on 2022-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasios', '0003_rename_nombreclasehorario_horarios_nombreclase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horarioClase',
            field=models.DateTimeField(),
        ),
    ]
