# Generated by Django 4.0.4 on 2022-06-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasios', '0005_alter_horarios_horarioclase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='nombreClase',
            new_name='nombreClaseH',
        ),
    ]
