# Generated by Django 4.0.5 on 2022-06-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasios', '0006_rename_nombreclase_horarios_nombreclaseh'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='profesorClase',
            field=models.CharField(default='hola', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clases',
            name='sucursalClase',
            field=models.CharField(default='hola', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesores',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
